---
language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

install:
  - go get ./...
  - go get github.com/alecthomas/gometalinter

before_script:
  - gometalinter --install

script:
  - go test -v ./...
  - gometalinter --tests . ./hammer