---
language: go

# we support the most two recent releases, and (hopefully) the tip.
go:
  - 1.4
  - 1.5
  - tip

install:
  - go get -v -t ./...
  - go get -v github.com/alecthomas/gometalinter

before_script:
  - gometalinter --install

script:
  - go test -v ./...
  - go get . && gometalinter --tests . ./hammer/...